# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~

    docker:
      - image: circleci/node:10.9.0

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install the dependencies
      - run:
          name: npm install
          command: |
            cd app/
            npm i

      # Cache the current app state
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "app/package.json" }}

      # Lint and Transpile the code
      - run:
          name: Lint and Transpile
          command: |
            cd app/
            npm run make

      # Run the Unit tests
      - run:
          name: Run Unit tests
          command: |
            cd app/
            npm run test-unit

      # Install Heroku CLI and sign in with it
      - run:
          name: Setup Heroku CLI
          command: ./scripts/setup-heroku.sh

      # Setup Docker engine for the build
      - setup_remote_docker

      # Execute the build
      - run:
          name: Build
          command: ./scripts/build.sh

      # Sign in Docker with Heroku's container registry and push the image to it
      - run:
          name: Push to Heroku container registry
          command: |
            docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
            docker tag registry.heroku.com/$HEROKU_APP_NAME:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

      # Deploy the app
      - run:
          name: Deploy
          command: |
            heroku container:release web --app $HEROKU_APP_NAME




